### ISSUE TITLE
Quick Start doesn't work because of "Cannot find module" error

### ISSUE THREAD

**Issue by zoulja** [c0bra/svelma#111]
Hello.
I've tried to build the app according to the readme.
My steps:
1. Install svelte
```
npx degit sveltejs/template my-svelte-project
cd my-svelte-project
npm install
```
2. Install svelma
```
npm install --save bulma svelma
npm install node-sass svelte-preprocess rollup-plugin-postcss --save-dev
```
3. Updated rollup config according to https://github.com/c0bra/svelma#2-add-the-postcss-plugin-to-your-rollup-config
4. Added svelma component according to https://github.com/c0bra/svelma#3-import-bulmas-css-and-svelma-components
5. Run '**npm run dev**'

**Expected result:**
Dev server is started, I can play with Svelma

**Actual result:**

```
user@localhost:~/my-svelte-project$ npm run dev

> svelte-app@1.0.0 dev
> rollup -c -w

[!] Error: Cannot find module 'rollup-plugin-postcss'
Require stack:
- /home/user/my-svelte-project/rollup.config.js
- /home/user/my-svelte-project/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/user/my-svelte-project/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'rollup-plugin-postcss'
Require stack:
- /home/user/my-svelte-project/rollup.config.js
- /home/user/my-svelte-project/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/user/my-svelte-project/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/user/my-svelte-project/rollup.config.js:11:15)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.require.extensions.<computed> [as .js] (/home/user/my-svelte-project/node_modules/rollup/dist/shared/loadConfigFile.js:540:20)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)

^C
```

Rollup config: [rollup.config.zip](https://github.com/c0bra/svelma/files/6416369/rollup.config.zip)

**Comment by abbychau** [comment]
tested that your rollup config is fine.
are you sure that you have `npm install node-sass svelte-preprocess rollup-plugin-postcss --save-dev` executed?

**Comment by zoulja** [comment]
I tried to reinstall from the scratch, but now get
```
...
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
...
```

error
Seems nodejs was recently updated and it broken something

**Comment by zoulja** [comment]
Seems it was solved after recent node-sass update
