### ISSUE TITLE
Error: PostCSS plugin postcss-noop-plugin requires PostCSS 8

### ISSUE THREAD

**Issue by ehemmerlin** [c0bra/svelma#82]
Following the installation guide for Rollup bundler, after installing the required npm packages, when postcss() is added to rollup.config.js the following error occurs.

```
 > svelte-app@1.0.0 dev /app
 > rollup -c -w
 
 rollup v2.35.1
 bundles src/main.js → public/build/bundle.js...
 [!] (plugin postcss) Error: PostCSS plugin postcss-noop-plugin requires PostCSS 8.
 Migration guide for end-users:
 https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
 src/App.css
 Error: PostCSS plugin postcss-noop-plugin requires PostCSS 8.
 Migration guide for end-users:
 https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
     at Processor.normalize (/app/node_modules/postcss/lib/processor.es6:139:15)
     at new Processor (/app/node_modules/postcss/lib/processor.es6:38:25)
     at Object.postcss (/app/node_modules/postcss/lib/postcss.es6:34:10)
     at /app/node_modules/rollup-plugin-postcss/dist/index.js:322:55
     at Generator.next (<anonymous>)
     at asyncGeneratorStep (/app/node_modules/rollup-plugin-postcss/dist/index.js:29:24)
     at _next (/app/node_modules/rollup-plugin-postcss/dist/index.js:51:9)
```

Links to the installation guides I used:
- https://c0bra.github.io/svelma/install/
- https://github.com/c0bra/svelma/blob/master/README.md#2-install-svelma-and-dependencies-via-npm

**Comment by akmalirfan** [comment]
Try adding `"postcss": "^8.2.4"` into your `devDependencies`

**Comment by abbychau** [comment]
rollup config and package.json are updated in the new version.
feel free to reopen it on any problem.
